### PR TITLE
485 484 bugs

### LINKED ISSUE #485: check if user has at least 1 memory before sharing is possible
Bildschirmfoto 2020-04-02 um 15 39 49

otherwise it doesn;t make sense to share memories

### PR DESCRIPTION
**Pull request by dupreesi**
fixes #485, #484

### CODE REVIEW

File: client/src/Components/Pages/ShareMemories/index.js [hunk 1]
```diff
@@ -82,14 +82,42 @@ const ShareMemories = ({ theme, name, history }) => {
...
+      });
     }
   };
 
+  // gets user memories and redirects to create memory if no memories exist
+  useEffect(() => {
+    const getMemories = async () => {
+      const { data: userMemories, error } = await memories.getAll({});
+
+      if (!error && userMemories) {
```
Comment (RamyAlshurafa) [inline client/src/Components/Pages/ShareMemories/index.js:101]: this can be handled this from the `memories.getAll` function to keep the component small as much as possible and logic-free
